# Generated by Django 6.1.1 on 2026-09-12 12:00

import django.db.models.deletion
import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название базы')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название цикла',
                'verbose_name_plural': 'Названия циклов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид финансирования',
                'verbose_name_plural': 'Виды финансирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('counts_in_hours', models.BooleanField(default=True, verbose_name='Участвует в подсчёте часов')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('max_hours_per_day', models.PositiveSmallIntegerField(default=0, help_text='0 — сотрудник не ведёт занятия.', verbose_name='Макс. часов в день')),
                ('can_sign', models.BooleanField(default=False, help_text='Например, зав. отделением.', verbose_name='Подписывает расписание')),
                ('can_approve', models.BooleanField(default=False, help_text='Например, зам. директора по ДПО.', verbose_name='Утверждает расписание')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Фамилия и инициалы, например: ИВАНОВ И.И. Регистр и пробелы нормализуются автоматически.', max_length=50, unique=True, validators=[timetable.models.validate_short_name], verbose_name='Короткое имя')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='timetable.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.base', verbose_name='База')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.cyclename', verbose_name='Название цикла')),
                ('approved_by', models.ForeignKey(limit_choices_to={'position__can_approve': True}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_cycles', to='timetable.employee', verbose_name='Утвердил')),
                ('funding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.fundingtype', verbose_name='Вид финансирования')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'ordering': ['-start_date', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cycle_end_after_start')],
            },
        ),
    ]
