# Generated by Django 6.1.1 on 2026-09-11 15:45

import django.db.models.deletion
import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('max_hours_per_day', models.PositiveSmallIntegerField(default=0, help_text='0 — сотрудник не ведёт занятия.', verbose_name='Макс. часов в день')),
                ('can_approve', models.BooleanField(default=False, verbose_name='Утверждает расписание')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Фамилия и инициалы, например: ИВАНОВ И.И. Регистр и пробелы нормализуются автоматически.', max_length=50, unique=True, validators=[timetable.models.validate_short_name], verbose_name='Короткое имя')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='timetable.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['short_name'],
            },
        ),
    ]
