# Generated by Django 6.1.1 on 2026-09-14 18:02

import django.db.models.deletion
import timetable.exports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название базы')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название цикла',
                'verbose_name_plural': 'Названия циклов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Фамилия и инициалы, например: ИВАНОВ И.И. Регистр и пробелы нормализуются автоматически.', max_length=50, unique=True, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид финансирования',
                'verbose_name_plural': 'Виды финансирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('counts_in_hours', models.BooleanField(default=True, verbose_name='Участвует в подсчёте часов')),
                ('category', models.CharField(blank=True, choices=[('lecture', 'Лекции'), ('seminar', 'Занятия семинарского типа'), ('practice', 'Практика')], help_text='Используется в отчёте «Распределение часов преподавателей». Оставьте пустым, если тип занятия не должен попадать в этот отчёт (например, экзамен или консультация).', max_length=20, verbose_name='Категория в отчёте')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('max_hours_per_day', models.PositiveSmallIntegerField(default=0, help_text='0 — сотрудник не ведёт занятия.', verbose_name='Макс. часов в день')),
                ('can_sign', models.BooleanField(default=False, help_text='Например, зав. отделением.', verbose_name='Подписывает расписание')),
                ('can_approve', models.BooleanField(default=False, help_text='Например, зам. директора по ДПО.', verbose_name='Утверждает расписание')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.base', verbose_name='База')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.cyclename', verbose_name='Название цикла')),
                ('compiled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_cycles', to='timetable.employee', verbose_name='Составил')),
                ('funding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.fundingtype', verbose_name='Вид финансирования')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Окончание')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Часы')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetable.cycle', verbose_name='Цикл')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.employee', verbose_name='Преподаватель')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.lessontype', verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='timetable.position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SlugField(help_text='Один из зарегистрированных кодов (см. exports/kinds.py).', max_length=32, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=timetable.exports.models.template_upload_path, verbose_name='Файл шаблона (.docx)')),
                ('is_active', models.BooleanField(default=True, help_text='Для каждого типа активен только один.', verbose_name='Активный')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['kind', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kind',), name='one_active_template_per_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cycle_end_after_start'),
        ),
    ]
