# Generated by Django 6.1.1 on 2026-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='can_sign',
            field=models.BooleanField(default=False, help_text='Например, зав. отделением.', verbose_name='Подписывает расписание'),
        ),
        migrations.AlterField(
            model_name='position',
            name='can_approve',
            field=models.BooleanField(default=False, help_text='Например, зам. директора по ДПО.', verbose_name='Утверждает расписание'),
        ),
    ]
