# Generated by Django 6.1.1 on 2026-09-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Окончание')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Часы')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetable.cycle', verbose_name='Цикл')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.employee', verbose_name='Преподаватель')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.lessontype', verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
