# Generated by Django 6.1.1 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='in_archive',
            field=models.BooleanField(default=False, help_text='Отметьте после выгрузки расписания, табеля и нагрузки. Архивированный цикл защищён от изменений.', verbose_name='В архиве'),
        ),
    ]
