# Generated by Django 6.1.1 on 2026-09-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_position_can_sign_alter_position_can_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название базы')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название цикла',
                'verbose_name_plural': 'Названия циклов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид финансирования',
                'verbose_name_plural': 'Виды финансирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('counts_in_hours', models.BooleanField(default=True, verbose_name='Участвует в подсчёте часов')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('approved_by', models.ForeignKey(limit_choices_to={'position__can_approve': True}, on_delete=django.db.models.deletion.PROTECT, related_name='approved_cycles', to='timetable.employee', verbose_name='Утвердил')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='timetable.cyclename', verbose_name='Название цикла')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'ordering': ['-start_date', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cycle_end_after_start')],
            },
        ),
    ]
