# Generated by Django 6.1.1 on 2026-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_cycle_in_archive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('name', 'base', 'start_date'), name='cycle_unique_name_base_start'),
        ),
    ]
