# Generated by Django 6.1.1 on 2026-09-13 05:26

import django.db.models.deletion
import timetable.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_cycle_approved_to_compiled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='compiled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_cycles', to='timetable.employee', verbose_name='Составил'),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('schedule', 'Расписание цикла'), ('load_summary', 'Сводка нагрузки')], max_length=32, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=timetable.models.template_upload_path, verbose_name='Файл шаблона (.docx)')),
                ('is_active', models.BooleanField(default=True, help_text='Используется для выгрузки. Для каждого типа активен только один.', verbose_name='Активный')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['kind', '-uploaded_at'],
            },
        ),
    ]
