# Generated by Django 6.1.1 on 2026-09-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_cycle_cycle_unique_name_base_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time_end',
        ),
    ]
