# Generated by Django 6.1.1 on 2026-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_lesson_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_hours_per_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым, если недельный лимит не задан — проверяется только дневной.', null=True, verbose_name='Макс. часов в неделю'),
        ),
        migrations.AddField(
            model_name='position',
            name='max_hours_per_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым, если годовой лимит не задан. Учебный год: с 1 сентября по дату окончания последнего цикла.', null=True, verbose_name='Макс. часов в учебном году'),
        ),
    ]
