# Generated by Django 6.1.1 on 2026-09-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_cycle_compiled_by_documenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Латиницей, без пробелов. Например: schedule, teacher_load.', max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='kind_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.documentkind'),
        ),
    ]
