# Generated by Django 6.1.1 on 2026-09-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_documentkind_documenttemplate_kind_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['kind_new', '-uploaded_at'], 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='kind',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.documentkind'),
        ),
    ]
