# Generated by Django 6.1.1 on 2026-09-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_position_max_hours_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttemplate',
            name='one_active_template_per_kind',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='is_active',
        ),
    ]
