# Generated by Django 6.1.1 on 2026-09-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_documenttemplate_one_active_template_per_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='base',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если занятие идёт на базе цикла. Заполните, если занятие проходит на другой базе.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.base', verbose_name='База'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='break_after_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Пауза между этим занятием и следующим. Слушателям нужно время, чтобы добраться до другой базы. 0 — занятия идут встык.', verbose_name='Перемена после урока, мин'),
        ),
    ]
