# Generated by Django 6.1.1 on 2026-09-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_documenttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['kind', '-uploaded_at'], 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='kind_new',
            new_name='kind',
        ),
    ]
