# Generated by Django 6.1.1 on 2026-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_documenttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='category',
            field=models.CharField(blank=True, choices=[('lecture', 'Лекции'), ('seminar', 'Занятия семинарского типа'), ('practice', 'Практика')], help_text='Используется в отчёте «Распределение часов преподавателей». Оставьте пустым, если тип занятия не должен попадать в этот отчёт (например, экзамен или консультация).', max_length=20, verbose_name='Категория в отчёте'),
        ),
    ]
