# Generated by Django 6.1.1 on 2026-09-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_lesson_base_lesson_break_after_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base',
            field=models.ForeignKey(blank=True, help_text='Основная база, где работает сотрудник. Оставьте пустым, если сотрудник не привязан к конкретной базе.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='timetable.base', verbose_name='База'),
        ),
    ]
