# Generated by Django 6.1.1 on 2026-10-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_employee_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
    ]
