# Generated by Django 6.1.1 on 2026-09-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_lessontype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.documentkind', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='short_name',
            field=models.CharField(help_text='Фамилия и инициалы, например: ИВАНОВ И.И. Регистр и пробелы нормализуются автоматически.', max_length=50, unique=True, verbose_name='Короткое имя'),
        ),
    ]
