# Generated by Django 6.1.1 on 2026-10-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_delete_documenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(max_length=255, unique=True, verbose_name='Полное название')),
                ('name_short', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['sort_order', 'name_short'],
            },
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('kind', models.CharField(choices=[('ПП', 'Профессиональная переподготовка'), ('ПК', 'Повышение квалификации')], max_length=2, verbose_name='Вид')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Часы')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_programs', to='timetable.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Рабочая программа',
                'verbose_name_plural': 'Рабочие программы',
                'ordering': ['-academic_year', 'kind', 'discipline__name_short'],
                'constraints': [models.UniqueConstraint(fields=('discipline', 'academic_year', 'kind', 'hours'), name='work_program_unique')],
            },
        ),
    ]
