# Generated by Django 6.1.1 on 2026-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_update_attestation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontype',
            name='counts_in_hours',
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='category',
            field=models.CharField(blank=True, choices=[('lecture', 'Лекции'), ('seminar', 'Занятия семинарского типа'), ('practice', 'Практика'), ('attestation', 'Итоговая аттестация')], help_text='Используется в отчёте «Распределение часов преподавателей». Оставьте пустым, если тип занятия не должен попадать в этот отчёт (например, экзамен или консультация).', max_length=20, verbose_name='Категория в отчёте'),
        ),
    ]
