# Generated by Django 6.1.1 on 2026-10-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_remove_lessontype_counts_in_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='in_archive',
        ),
    ]
