# Generated by Django 6.1.1 on 2026-10-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_cycle_in_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='kind',
            field=models.CharField(blank=True, choices=[('ПП', 'Профессиональная переподготовка'), ('ПК', 'Повышение квалификации')], default='', help_text='ПП — профессиональная переподготовка, ПК — повышение квалификации. ', max_length=2, verbose_name='Вид программы'),
        ),
    ]
