# Generated by Django 6.1.1 on 2026-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_cycle_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cycle',
            name='cycle_unique_name_base_start',
        ),
        migrations.AddField(
            model_name='cycle',
            name='stream',
            field=models.CharField(blank=True, default='', help_text='Номер или название потока. Оставьте пустым, если поток не различается.', max_length=50, verbose_name='Поток'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='kind',
            field=models.CharField(blank=True, choices=[('ПП', 'ПП'), ('ПК', 'ПК')], default='', help_text='ПП — профессиональная переподготовка. ПК — повышение квалификации.', max_length=2, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='kind',
            field=models.CharField(choices=[('ПП', 'ПП'), ('ПК', 'ПК')], help_text='ПП — профессиональная переподготовка. ПК — повышение квалификации.', max_length=2, verbose_name='Вид'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('name', 'base', 'start_date', 'stream'), name='cycle_unique_name_base_start_stream'),
        ),
    ]
