# Generated by Django 6.1.1 on 2026-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_remove_cycle_cycle_unique_name_base_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(blank=True, choices=[('lecture', 'Лекции'), ('seminar', 'Занятия семинарского типа'), ('practice', 'Практика'), ('attestation', 'Итоговая аттестация')], default='', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Группа'),
        ),
    ]
